### ISSUE TITLE
Schema being cleared when exiting playground

### ISSUE THREAD

**Issue by DefinitelyNotAnAssassin** [Finestwork/my-schema-flow#34]
![image](https://github.com/Finestwork/my-schema-flow/assets/46719110/c3fc93f6-13be-4cb0-996d-9afab83d1f2a)
![image](https://github.com/Finestwork/my-schema-flow/assets/46719110/0ceb98ac-e029-458f-b188-dd289e1d4f1e)
![image](https://github.com/Finestwork/my-schema-flow/assets/46719110/e52ef7a7-c3a3-46bb-bd23-3cfed2e4eb13)

Maybe when the exit button is clicked we can go to the last index of the history?

**Comment by Finestwork** [comment]
Ohhhh! I forgot this one. Thank you, @DefinitelyNotAnAssassin! The reason I deleted the schema is because VueFlow prevents users from typing whitespace using shift + spacebar, so removing them from the DOM solves the problem. One of the solutions I'm considering is temporarily storing the nodes in the store so that we can retrieve them later on.
