### ISSUE TITLE
[Playground] Invalid Keyword Disables the User to Query

### ISSUE THREAD

**Issue by DefinitelyNotAnAssassin** [Finestwork/my-schema-flow#35]
![image](https://github.com/Finestwork/my-schema-flow/assets/46719110/e0a0dfc5-46b1-40e4-b180-7a7eb8fa066b)
![image](https://github.com/Finestwork/my-schema-flow/assets/46719110/63246d08-91a2-4b38-ad34-1fe235b88d2c)

After the query has been executed, the Playground shows a  loading screen that is not being completed, therefore not allowing the user to run a query again. This happens when an invalid keyword has been executed 

![image](https://github.com/Finestwork/my-schema-flow/assets/46719110/fd972817-3068-4f8d-94cf-6dba21243d1b)

**Comment by Finestwork** [comment]
Hello, @DefinitelyNotAnAssassin! I've disabled the 'USE' keyword to prevent users from switching databases on the fly. They've already selected a database before using our text editor—making the 'USE' keyword inapplicable in this context. I think, the issue is not in the main process but in `MainContent.vue`.

Progress bar and `isRunning` variable should be disabled here:
![image](https://github.com/Finestwork/my-schema-flow/assets/62718854/e55943c7-88be-4551-a0a7-0bb4576d983d)
